# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d2e8247f2c26a429c5ac4101c1d702ac334bfc5ba8f2c00ec426221cc33bdfa7c897d2eed0e3c995e465c0d8aeecb05ce1917c6a1110a32006621556f8295d5

test:
  secret_key_base: 260914d18ea40326cdcc1eb546169c474dce1db159bb54b748111751fc8f9bd8590e5705873d1f3ab0ad085705f61ec2468299abadc5d6364cda2eb910328268

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
